Repository Linkup-3mw/backend, pull requests merged in 2024-06, with the labels that each got.

#53 [FEAT] Feature/#52 reservation manager
  src/main/java/com/core/linkup/club/entity/Club.java
  src/main/java/com/core/linkup/common/controller/CategoryController.java
  src/main/java/com/core/linkup/common/entity/BaseEntity.java
  src/main/java/com/core/linkup/common/entity/BaseMembershipEntity.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/membership/company/converter/CompanyMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/company/repository/CompanyMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/java/com/core/linkup/reservation/membership/individual/converter/IndividualMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/IndividualMembership.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/enums/MembershipType.java
  src/main/java/com/core/linkup/reservation/membership/individual/repository/IndividualMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/individual/response/IndividualMembershipResponse.java
  src/main/java/com/core/linkup/reservation/membership/individual/service/IndividualMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/controller/CompanyMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/IndividualMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/entity/Reservation.java
  src/main/java/com/core/linkup/reservation/reservation/entity/enums/ReservationType.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepository.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/response/CompanyMembershipRegistrationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/CompanyMembershipReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/IndividualMembershipReservationListResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/MembershipReservationListResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/MembershipResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/ReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/SeatSpaceResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/MembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: feat

#55 소모임 가입 관련
  src/main/java/com/core/linkup/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/entity/ClubAnswer.java
  src/main/java/com/core/linkup/club/entity/ClubMember.java
  src/main/java/com/core/linkup/club/entity/ClubQuestion.java
  src/main/java/com/core/linkup/club/repository/ClubAnswerRepository.java
  src/main/java/com/core/linkup/club/repository/ClubCustomRepository.java
  src/main/java/com/core/linkup/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/repository/ClubMemberRepository.java
  src/main/java/com/core/linkup/club/repository/ClubQuestionRepository.java
  src/main/java/com/core/linkup/club/request/ClubQuestionRequest.java
  src/main/java/com/core/linkup/club/requset/ClubAnswerRequest.java
  src/main/java/com/core/linkup/club/requset/ClubApplicationRequest.java
  src/main/java/com/core/linkup/club/requset/ClubCreateRequest.java
  src/main/java/com/core/linkup/club/requset/ClubQuestionRequest.java
  src/main/java/com/core/linkup/club/response/ClubAnswerResponse.java
  src/main/java/com/core/linkup/club/response/ClubApplicationResponse.java
  src/main/java/com/core/linkup/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/service/ClubService.java
Labels: feat

#57 [FEAT] Feature/#54 company reservation manager
  src/main/java/com/core/linkup/common/config/RedisConfig.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
  src/main/java/com/core/linkup/office/entity/enums/SeatSpaceType.java
  src/main/java/com/core/linkup/office/repository/SeatSpaceRepository.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/controller/CompanyMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/IndividualMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/response/SeatSpaceResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: feat

#59 [REFACTOR] Refactor/#58 registration validation, cookie ttl
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/java/com/core/linkup/security/jwt/JwtProvider.java
Labels: refactoring

#62 [FIX] #50 - 공유오피스 전체 조회 기능 수정
  src/main/java/com/core/linkup/office/controller/OfficeController.java
  src/main/java/com/core/linkup/office/repository/OfficeSearchRepository.java
  src/main/java/com/core/linkup/office/repository/OfficeSearchRepositoryImpl.java
  src/main/java/com/core/linkup/office/request/OfficeSearchControllerRequest.java
  src/main/java/com/core/linkup/office/request/OfficeSearchRequest.java
  src/main/java/com/core/linkup/office/service/OfficeService.java
Labels: fix

#61 소모임 공지사항 등록/수정/삭제
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubNoticeController.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubNoticeConverter.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeRepository.java
  src/main/java/com/core/linkup/club/clubnotice/request/ClubNoticeRequest.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubNoticeResponse.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
  src/main/java/com/core/linkup/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/entity/Club.java
  src/main/java/com/core/linkup/club/entity/ClubBoard.java
  src/main/java/com/core/linkup/club/entity/ClubComment.java
  src/main/java/com/core/linkup/club/entity/ClubMeeting.java
  src/main/java/com/core/linkup/club/entity/ClubNotice.java
  src/main/java/com/core/linkup/club/entity/enums/NotificationType.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat

#64 [FIX] #56 - 소모임 공지 소유자정보 추가
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubNoticeConverter.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubNoticeResponse.java
Labels: feat

#65 [REFACTOR] Refactor/#60 reservation validation
  src/main/java/com/core/linkup/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/linkup/office/converter/OfficeConverter.java
  src/main/java/com/core/linkup/office/entity/OfficeBuilding.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/request/ReservationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/response/ReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationValidationService.java
Labels: refactoring

#67 Feature/#56 club notice
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubBoardController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubCommentController.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubBoardConverter.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubCommentConverter.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentRepository.java
  src/main/java/com/core/linkup/club/clubnotice/request/ClubBoardRequest.java
  src/main/java/com/core/linkup/club/clubnotice/request/ClubCommentRequest.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubBoardResponse.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubCommentResponse.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubBoardService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubCommentService.java
  src/main/java/com/core/linkup/club/entity/ClubComment.java
  src/main/java/com/core/linkup/club/entity/enums/NotificationType.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat

#69 [FIX] fix #68 authentication header
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/security/Tokens.java
  src/main/java/com/core/linkup/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/linkup/security/jwt/JwtProperties.java
  src/main/java/com/core/linkup/security/jwt/JwtRefreshTokenFilter.java
Labels: fix

#70 [FIX] CORS 업데이트
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/config/WebConfig.java
Labels: deployment

#74 [FIX] CICD 수정
  .github/workflows/cicd.yml
  src/main/resources/application-test.yml
Labels: deployment

#77 [FEAT] #56 - 정기모임 수정/삭제 추가
  src/main/java/com/core/linkup/club/clubmeeting/controller/ClubMeetingController.java
  src/main/java/com/core/linkup/club/clubmeeting/converter/ClubMeetingConverter.java
  src/main/java/com/core/linkup/club/clubmeeting/entity/ClubMeeting.java
  src/main/java/com/core/linkup/club/clubmeeting/repository/ClubMeetingRepository.java
  src/main/java/com/core/linkup/club/clubmeeting/service/ClubMeetingService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat

#78 [FIX] Company reservation manager fix
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/entity/enums/ReservationType.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: fix

#73 [REFACTOR] #71 동시성 관리 추가
  src/main/java/com/core/linkup/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/reservation/entity/Reservation.java
Labels: refactoring

#79 Feature/#63 refactoring club
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/Club.java
  src/main/java/com/core/linkup/club/club/entity/ClubAnswer.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepository.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/club/request/ClubCreateRequest.java
  src/main/java/com/core/linkup/club/club/response/ClubApplicationResponse.java
  src/main/java/com/core/linkup/club/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubBoardController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubNoticeController.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubNoticeConverter.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepository.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeRepository.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubBoardService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat, fix

#80 [FEAT] Feature/#75 main page reservation api
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/response/MainPageReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/MembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationValidationService.java
Labels: feat

#82 [FIX] Fix/#81 available space api
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/response/SeatSpaceResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: fix, refactoring

#85 [FIX] #84 소모임 게시글 타입 오류
  src/main/java/com/core/linkup/club/clubnotice/entity/ClubNotice.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepositoryImpl.java
Labels: fix

#83 Feature/#63 refactoring club(clubLike)
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/ClubLike.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepository.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/club/repository/ClubLikeRepository.java
  src/main/java/com/core/linkup/club/club/request/ClubLikeRequest.java
  src/main/java/com/core/linkup/club/club/response/ClubLikeResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/club/clubmeeting/repository/ClubMeetingRepository.java
  src/main/java/com/core/linkup/club/clubnotice/entity/ClubNotice.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat

#86 [FIX] #63 - 소모임 좋아요 등록/삭제 수정
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/ClubLike.java
  src/main/java/com/core/linkup/club/club/response/ClubLikeResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
Labels: fix

#88 [REFACTOR] Refactor/#87 club like
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/ClubLike.java
  src/main/java/com/core/linkup/club/club/repository/ClubLikeRepository.java
  src/main/java/com/core/linkup/club/club/request/ClubLikeRequest.java
  src/main/java/com/core/linkup/club/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/common/entity/BaseMembershipEntity.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/membership/company/converter/CompanyMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/java/com/core/linkup/reservation/membership/individual/converter/IndividualMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/individual/service/IndividualMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/controller/CompanyMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/response/MembershipResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
Labels: fix, refactoring

#90 [REFACTOR] #87 소모임 전체조회 시 좋아요 여부 반영된 api 분리
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/repository/ClubLikeRepository.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
Labels: fix, refactoring

#91 Feature/#89 club member
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/repository/ClubAnswerRepository.java
  src/main/java/com/core/linkup/club/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: fix

#94 [FIX] #93 - 소모임 호스트도 공지 등록 할수 있도록 수정
  src/main/java/com/core/linkup/club/clubmeeting/converter/ClubMeetingConverter.java
  src/main/java/com/core/linkup/club/clubmeeting/service/ClubMeetingService.java
Labels: fix

#96 [FIX] #95 소모임 카테고리 필터링
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/Club.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepository.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
Labels: fix

#100 [REFACTOR] Refactor/#99 club comment
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubCommentController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubNoticeController.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubBoardConverter.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubCommentConverter.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubNoticeConverter.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentRepository.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepository.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubBoardResponse.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubCommentResponse.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubNoticeResponse.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubBoardService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubCommentService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
Labels: fix, refactoring

#103 [FIX] #102 - clubResponse에 club detailedIntroduction 추가
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubBoardConverter.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubBoardResponse.java
Labels: fix

#105 [REFACTOR] Refactor/#104 available seat
  src/main/java/com/core/linkup/club/clubnotice/entity/enums/NotificationType.java
  src/main/java/com/core/linkup/common/utils/EmailUtils.java
  src/main/java/com/core/linkup/member/service/ValidationService.java
  src/main/java/com/core/linkup/office/entity/enums/SeatSpaceType.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/enums/MembershipType.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/entity/enums/ReservationType.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: fix, refactoring

#108 [FEAT] Feature/#107 club approval
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/controller/ClubMemberController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/entity/ClubMember.java
  src/main/java/com/core/linkup/club/club/repository/ClubMemberRepository.java
  src/main/java/com/core/linkup/club/club/request/ClubCreateRequest.java
  src/main/java/com/core/linkup/club/club/request/ClubMemberApprovalRequest.java
  src/main/java/com/core/linkup/club/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/club/service/ClubMemberService.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: feat, refactoring

#113 [REFACTOR] Refactor/#60 reservation validator
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/reservation/controller/CompanyMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/IndividualMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepository.java
  src/main/java/com/core/linkup/reservation/reservation/request/MultipleReservationsRequest.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationValidationService.java
Labels: refactoring

#117 [FIX] Fix/#114 club refactor
  .gitignore
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/club/service/ClubService.java
  src/main/java/com/core/linkup/club/clubmeeting/service/ClubMeetingService.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubBoardController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubNoticeController.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubBoardConverter.java
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubNoticeConverter.java
  src/main/java/com/core/linkup/club/clubnotice/entity/ClubNotice.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/clubnotice/request/ClubBoardRequest.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubBoardResponse.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubNoticeResponse.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubBoardService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: fix, refactoring, deployment

#119 [FIX] comment response - name changed to username
  src/main/java/com/core/linkup/club/clubnotice/converter/ClubCommentConverter.java
  src/main/java/com/core/linkup/club/clubnotice/response/ClubCommentResponse.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubCommentService.java
Labels: fix

#120 [FIX] 댓글 작성자 이름 표기 수정
  src/main/java/com/core/linkup/club/clubnotice/service/ClubCommentService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: fix

#128 [FIX] Refactor/#127 club fixes
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentCustomRepository.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentRepository.java
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubNoticeCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubCommentService.java
  src/main/java/com/core/linkup/club/clubnotice/service/ClubNoticeService.java
Labels: fix, refactoring

#130 [FEAT] Feature/#129 most recent reservation
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/response/MembershipReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
Labels: feat

#140 [FIX] #138 - 댓글 정렬 id 순으로 수정
  src/main/java/com/core/linkup/club/clubnotice/repository/ClubCommentCustomRepositoryImpl.java
Labels: fix

#142 [DOC] #141 Swagger 추가
  src/main/java/com/core/linkup/club/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/club/controller/ClubMemberController.java
  src/main/java/com/core/linkup/club/clubmeeting/controller/ClubMeetingController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubCommentController.java
  src/main/java/com/core/linkup/club/clubnotice/controller/ClubNoticeController.java
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/config/SwaggerConfig.java
  src/main/java/com/core/linkup/common/controller/CategoryController.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/office/controller/OfficeController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/CompanyMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/IndividualMembershipReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
Labels: documentation

#143 [FIX] #141 build.gradle 수정
  build.gradle
Labels: documentation, fix
