Repository Linkup-3mw/backend, pull requests merged in 2024-05, with the labels that each got.

#6 [FEAT] Feature/#1 auth
  .gitignore
  build.gradle
  src/main/java/com/core/linkup/common/annotation/Converter.java
  src/main/java/com/core/linkup/common/config/EmailConfig.java
  src/main/java/com/core/linkup/common/config/ObjectMapperConfig.java
  src/main/java/com/core/linkup/common/config/RedisConfig.java
  src/main/java/com/core/linkup/common/config/S3Config.java
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/entity/BaseEntity.java
  src/main/java/com/core/linkup/common/properties/EmailProperties.java
  src/main/java/com/core/linkup/common/service/RedisService.java
  src/main/java/com/core/linkup/common/service/S3Service.java
  src/main/java/com/core/linkup/common/utils/CookieUtils.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/converter/MemberConverter.java
  src/main/java/com/core/linkup/member/entity/Member.java
  src/main/java/com/core/linkup/member/entity/enums/GenderType.java
  src/main/java/com/core/linkup/member/entity/enums/IndustryType.java
  src/main/java/com/core/linkup/member/entity/enums/OccupationType.java
  src/main/java/com/core/linkup/member/entity/enums/RoleType.java
  src/main/java/com/core/linkup/member/repository/MemberRepository.java
  src/main/java/com/core/linkup/member/request/LoginRequest.java
  src/main/java/com/core/linkup/member/request/Loginable.java
  src/main/java/com/core/linkup/member/request/MemberModificationRequest.java
  src/main/java/com/core/linkup/member/request/RegistrationRequest.java
  src/main/java/com/core/linkup/member/request/validate/EmailValidateRequest.java
  src/main/java/com/core/linkup/member/request/validate/EmailVerificationRequest.java
  src/main/java/com/core/linkup/member/request/validate/PasswordValidateRequest.java
  src/main/java/com/core/linkup/member/request/validate/UsernameValidateRequest.java
  src/main/java/com/core/linkup/member/response/MemberResponse.java
  src/main/java/com/core/linkup/member/service/MailService.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/security/MemberDetails.java
  src/main/java/com/core/linkup/security/MemberDetailsService.java
  src/main/java/com/core/linkup/security/Tokens.java
  src/main/java/com/core/linkup/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/linkup/security/jwt/JwtProperties.java
  src/main/java/com/core/linkup/security/jwt/JwtProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: development

#8 [FEAT] Feature/#7 common response
  src/main/java/com/core/linkup/common/exception/BaseException.java
  src/main/java/com/core/linkup/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/common/utils/EmailUtils.java
  src/main/java/com/core/linkup/common/utils/RedisUtils.java
  src/main/java/com/core/linkup/common/utils/S3Utils.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/repository/MemberRepository.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/security/jwt/JwtAuthenticationFilter.java
Labels: chore

#9 [FEAT] Feature/#7 common response
  src/main/java/com/core/linkup/common/exception/BaseException.java
  src/main/java/com/core/linkup/common/exception/GlobalExceptionHandler.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/common/utils/EmailUtils.java
  src/main/java/com/core/linkup/common/utils/RedisUtils.java
  src/main/java/com/core/linkup/common/utils/S3Utils.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/repository/MemberRepository.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/security/jwt/JwtAuthenticationFilter.java
Labels: chore

#10 [ADD] BaseResponse 적용
  src/main/java/com/core/linkup/common/response/BaseResponse.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
Labels: chore

#13 [FEAT] Querydsl 의존성, 설정 추가
  build.gradle
  src/main/java/com/core/linkup/common/config/QueryDslConfig.java
Labels: chore

#14 [FEAT] office 관련 Entity 추가
  build.gradle
  src/main/java/com/core/linkup/office/entity/OfficeBuilding.java
  src/main/java/com/core/linkup/office/entity/OfficeDetail.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
Labels: feat

#16 빌딩 지점 조회기능
  build.gradle
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/entity/BaseEntity.java
  src/main/java/com/core/linkup/common/entity/enums/CityType.java
  src/main/java/com/core/linkup/common/entity/enums/GenderType.java
  src/main/java/com/core/linkup/common/entity/enums/IndustryType.java
  src/main/java/com/core/linkup/common/entity/enums/OccupationType.java
  src/main/java/com/core/linkup/common/entity/enums/RoleType.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/member/entity/Member.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/office/Service/OfficeService.java
  src/main/java/com/core/linkup/office/controller/OfficeController.java
  src/main/java/com/core/linkup/office/entity/OfficeBuilding.java
  src/main/java/com/core/linkup/office/entity/OfficeDetail.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
  src/main/java/com/core/linkup/office/repository/OfficeRepository.java
  src/main/java/com/core/linkup/office/repository/OfficeSearchRepository.java
  src/main/java/com/core/linkup/office/repository/OfficeSearchRepositoryImpl.java
  src/main/java/com/core/linkup/office/request/OfficeSearchRequest.java
  src/main/java/com/core/linkup/office/response/OfficeDetailSearchResponse.java
  src/main/java/com/core/linkup/office/response/OfficeResponse.java
  src/main/java/com/core/linkup/office/response/OfficeSearchResponse.java
  src/main/java/com/core/linkup/security/MemberDetails.java
Labels: feat

#25 [FEAT] Feature/#24 category view endpoints
  src/main/java/com/core/linkup/category/controller/CategoryController.java
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/entity/enums/ClubType.java
  src/main/java/com/core/linkup/common/entity/enums/IndustryType.java
  src/main/java/com/core/linkup/common/entity/enums/OccupationType.java
  src/main/java/com/core/linkup/member/converter/MemberConverter.java
  src/main/java/com/core/linkup/member/entity/Member.java
  src/main/java/com/core/linkup/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/linkup/security/jwt/JwtRefreshTokenFilter.java
Labels: feat

#27 [FEAT] Feature/#26 company membership
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/common/utils/RedisUtils.java
  src/main/java/com/core/linkup/member/controller/MemberController.java
  src/main/java/com/core/linkup/member/converter/MemberConverter.java
  src/main/java/com/core/linkup/member/entity/Member.java
  src/main/java/com/core/linkup/member/request/RegistrationRequest.java
  src/main/java/com/core/linkup/member/response/MemberResponse.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/member/service/ValidationService.java
  src/main/java/com/core/linkup/reservation/membership/company/converter/CompanyMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/company/entity/Company.java
  src/main/java/com/core/linkup/reservation/membership/company/entity/CompanyMembership.java
  src/main/java/com/core/linkup/reservation/membership/company/repository/CompanyMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/company/response/CompanyMembershipResponse.java
  src/main/java/com/core/linkup/reservation/membership/company/response/CompanyResponse.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyService.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/IndividualMembership.java
  src/main/java/com/core/linkup/reservation/membership/individual/response/IndividualMembershipResponse.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/request/CompanyMembershipRegistrationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/response/CompanyMembershipRegistrationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/security/jwt/JwtRefreshTokenFilter.java
Labels: feat

#31 Feature/#21 officefiltering
  src/main/java/com/core/linkup/common/entity/enums/CityType.java
  src/main/java/com/core/linkup/office/controller/OfficeController.java
  src/main/java/com/core/linkup/office/converter/OfficeConverter.java
  src/main/java/com/core/linkup/office/entity/OfficeBuilding.java
  src/main/java/com/core/linkup/office/entity/OfficeDetail.java
  src/main/java/com/core/linkup/office/repository/OfficeSearchRepositoryImpl.java
  src/main/java/com/core/linkup/office/request/OfficeSearchControllerRequest.java
  src/main/java/com/core/linkup/office/request/OfficeSearchRequest.java
  src/main/java/com/core/linkup/office/response/OfficeDetailSearchResponse.java
  src/main/java/com/core/linkup/office/response/OfficeResponse.java
  src/main/java/com/core/linkup/office/response/OfficeSearchResponse.java
  src/main/java/com/core/linkup/office/service/OfficeService.java
Labels: feat

#32 [FEAT] Feature/#28 individual membership
  src/main/java/com/core/linkup/office/controller/OfficeController.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
  src/main/java/com/core/linkup/office/entity/enums/SeatSpaceType.java
  src/main/java/com/core/linkup/office/repository/SeatSpaceRepository.java
  src/main/java/com/core/linkup/office/service/OfficeService.java
  src/main/java/com/core/linkup/reservation/membership/company/repository/CompanyMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/individual/converter/IndividualMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/IndividualMembership.java
  src/main/java/com/core/linkup/reservation/membership/individual/repository/IndividualMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/individual/request/IndividualMembershipRequest.java
  src/main/java/com/core/linkup/reservation/membership/individual/service/IndividualMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/entity/Reservation.java
  src/main/java/com/core/linkup/reservation/reservation/request/IndividualMembershipRegistrationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/request/ReservationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/response/IndividualMembershipRegistrationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/ReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/TotalReservationService.java
Labels: feat

#34 소모임 등록 기능 추가, 개인 멤버십 등록 기능 수정
  src/main/java/com/core/linkup/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/entity/Club.java
  src/main/java/com/core/linkup/club/entity/ClubAnswer.java
  src/main/java/com/core/linkup/club/entity/ClubBoard.java
  src/main/java/com/core/linkup/club/entity/ClubComment.java
  src/main/java/com/core/linkup/club/entity/ClubMeeting.java
  src/main/java/com/core/linkup/club/entity/ClubMember.java
  src/main/java/com/core/linkup/club/entity/ClubQuestion.java
  src/main/java/com/core/linkup/club/repository/ClubRepository.java
  src/main/java/com/core/linkup/club/request/ClubRequest.java
  src/main/java/com/core/linkup/club/response/ClubsResponse.java
  src/main/java/com/core/linkup/club/service/ClubService.java
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/java/com/core/linkup/common/entity/enums/CategoryType.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/office/service/OfficeService.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/enums/MembershipType.java
  src/main/java/com/core/linkup/reservation/membership/individual/service/IndividualMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/entity/enums/ReservationType.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/TotalReservationService.java
Labels: feat

#35 [FEAT] #29 CI/CD 파이프라인 구축
  .github/workflow/cicd.yml
  Dockerfile
  src/main/java/com/core/linkup/common/config/SecurityConfig.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: feat

#47 소모임 curd
  src/main/java/com/core/linkup/club/controller/ClubController.java
  src/main/java/com/core/linkup/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/entity/Club.java
  src/main/java/com/core/linkup/club/entity/ClubQuestion.java
  src/main/java/com/core/linkup/club/repository/ClubCustomRepository.java
  src/main/java/com/core/linkup/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/repository/ClubRepository.java
  src/main/java/com/core/linkup/club/request/ClubQuestionRequest.java
  src/main/java/com/core/linkup/club/request/ClubRequest.java
  src/main/java/com/core/linkup/club/requset/ClubCreateRequest.java
  src/main/java/com/core/linkup/club/requset/ClubSearchRequest.java
  src/main/java/com/core/linkup/club/requset/ClubUpdateRequest.java
  src/main/java/com/core/linkup/club/response/ClubSearchResponse.java
  src/main/java/com/core/linkup/club/response/ClubsResponse.java
  src/main/java/com/core/linkup/club/service/ClubService.java
  src/main/java/com/core/linkup/common/entity/BaseEntity.java
  src/main/java/com/core/linkup/common/entity/enums/CategoryType.java
  src/main/java/com/core/linkup/common/entity/enums/ClubType.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/enums/MembershipType.java
  src/main/java/com/core/linkup/reservation/reservation/entity/enums/ReservationType.java
Labels: feat

#49 소모임 수정시 멤버 확인
  src/main/java/com/core/linkup/club/converter/ClubConverter.java
  src/main/java/com/core/linkup/club/repository/ClubCustomRepositoryImpl.java
  src/main/java/com/core/linkup/club/requset/ClubSearchRequest.java
  src/main/java/com/core/linkup/club/service/ClubService.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
Labels: refactoring

#51 [FEAT] Feature/#38 reservation - select individual membership, reservations
  src/main/java/com/core/linkup/common/entity/BaseMembershipEntity.java
  src/main/java/com/core/linkup/common/response/BaseResponseStatus.java
  src/main/java/com/core/linkup/member/converter/MemberConverter.java
  src/main/java/com/core/linkup/member/entity/Member.java
  src/main/java/com/core/linkup/member/service/MemberService.java
  src/main/java/com/core/linkup/office/entity/SeatSpace.java
  src/main/java/com/core/linkup/office/entity/enums/SeatSpaceType.java
  src/main/java/com/core/linkup/office/repository/OfficeRepository.java
  src/main/java/com/core/linkup/reservation/membership/company/converter/CompanyConverter.java
  src/main/java/com/core/linkup/reservation/membership/company/converter/CompanyMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/company/entity/Company.java
  src/main/java/com/core/linkup/reservation/membership/company/entity/CompanyMembership.java
  src/main/java/com/core/linkup/reservation/membership/company/repository/CompanyRepository.java
  src/main/java/com/core/linkup/reservation/membership/company/request/CompanyMembershipRequest.java
  src/main/java/com/core/linkup/reservation/membership/company/response/CompanyMembershipResponse.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyMembershipService.java
  src/main/java/com/core/linkup/reservation/membership/company/service/CompanyService.java
  src/main/java/com/core/linkup/reservation/membership/individual/converter/IndividualMembershipConverter.java
  src/main/java/com/core/linkup/reservation/membership/individual/entity/IndividualMembership.java
  src/main/java/com/core/linkup/reservation/membership/individual/repository/IndividualMembershipRepository.java
  src/main/java/com/core/linkup/reservation/membership/individual/request/IndividualMembershipRequest.java
  src/main/java/com/core/linkup/reservation/membership/individual/response/IndividualMembershipResponse.java
  src/main/java/com/core/linkup/reservation/membership/individual/service/IndividualMembershipService.java
  src/main/java/com/core/linkup/reservation/reservation/controller/ReservationController.java
  src/main/java/com/core/linkup/reservation/reservation/converter/ReservationConverter.java
  src/main/java/com/core/linkup/reservation/reservation/entity/Reservation.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepository.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/core/linkup/reservation/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/core/linkup/reservation/reservation/request/IndividualMembershipRegistrationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/request/MultipleReservationsRequest.java
  src/main/java/com/core/linkup/reservation/reservation/request/ReservationRequest.java
  src/main/java/com/core/linkup/reservation/reservation/response/CompanyMembershipReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/IndividualMembershipReservationListResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/ReservationResponse.java
  src/main/java/com/core/linkup/reservation/reservation/response/SeatSpaceResponse.java
  src/main/java/com/core/linkup/reservation/reservation/service/CompanyMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/IndividualMembershipReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/ReservationService.java
  src/main/java/com/core/linkup/reservation/reservation/service/TotalReservationService.java
Labels: feat
